name: Build and Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and build
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@master
        with:
          name: artifact
          path: public/
# agregado          
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: Create.npmrc
        shell: bash
        run: |
          echo "registry=https://jalartifactory.jfrog.io/artifactory/covid-19/" > .npmrc
          echo "_auth = ${{ secrets.ARTIFACTORY_TOKEN }}" >> .npmrc
          echo "always-auth = true" >> .npmrc
   
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
         node-version: '16.13.0'
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: login to jfrog
      uses: jfrog/setup-jfrog-cli@v1
      env:
        ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
    - run: |
        jfrog --version
        jfrog rt u "public/" default-npm-local
#        jfrog rt u -r covid-19 -u ${{ secrets.ARTIFACTORY_TOKEN }} -c public/

