name: Build and Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and build
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@master
        with:
          name: artifact
          path: public/

#  push:
#    runs-on: ubuntu-latest
#    needs: build
