name: Build and Publish

on: [push]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: npm install and build webpack
          run: |
            npm install
            npm run build
        - uses: actions/upload-artifact@main
          with:
            name: webpack artifacts
            path: build/
        - name: login to jfrog
          uses: jfrog/setup-jfrog-cli@v1
          env:
            ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
            API_KEY_NPM_JFROG: ${{secrets.API_KEY_NPM_JFROG}}
            run: |
                jfrog rt dl build/
                jfrog rt u aether build/
                jfrog rt bp

    #npm config set registry https://devopslv.jfrog.io/artifactory/api/npm/default-npm-virtual/
    #curl -uadmin: API_KEY_NPM_JFROG http://devopslv.jfrog.io:8081/artifactory/api/npm/auth
    #npm install request
    #npm publish
    #jfrog config add artifact --url=https://devopslv.jfrog.io/artifactory/default-npm-virtual/api/npm
    #jfrog rt u "public" default-npm-remote
