name: Build and Publish

on: [push]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: npm install and build webpack
          run: |
            npm install
            npm run build
        - uses: actions/upload-artifact@main
          with:
            name: webpack artifacts
            path: build/
  # agregado          
        - name: 'Checkout'
          uses: actions/checkout@v2
        - name: Create.npmrc
          shell: bash
          run: |
            echo "registry=https://jalartifactory.jfrog.io/artifactory/covid-19/" > .npmrc
            echo "_auth = ${{ secrets.ARTIFACTORY_TOKEN }}" >> .npmrc
            echo "always-auth = true" >> .npmrc
    
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
           node-version: '16.13.0'
    push:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: login to jfrog
        uses: jfrog/setup-jfrog-cli@v1
        env:
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          API_KEY_NPM_JFROG: ${{secrets.API_KEY_NPM_JFROG}}
      - run: |
          jfrog rt dl build/
          jfrog rt u "build/" default-npm-virtual
          npm config set registry https://jalartifactory.jfrog.io/artifactory/api/npm/default-npm-virtual/
          curl -uadmin: API_KEY_NPM_JFROG http://jalartifactory.jfrog.io:8081/artifactory/api/npm/auth
          npm install request
          npm publish
          jfrog config add artifact --url=https://jalartifactory.jfrog.io/artifactory/default-npm-virtual/api/npm
          jfrog rt u "build" default-npm-remote
         

